### ISSUE TITLE
!secret landroid_ip

### ISSUE THREAD

**Issue by MartianMH1** [Barma-lej/halandroid#2]
In the YAML is the IP defined as

`        value_template: !secret landroid_ip`

Is this intended? Since for this we'd had to define it in the Secrets-File?

**Comment by vistalba** [comment]
I didn't get it too. What should be in the secrets file? Why should I specify the IP manually? Or what is the idea of this?

**Comment by Barma-lej** [comment]
Since Landroid Cloud Integration does not give an IP address, serial number and MAC address, I set them in secrets.yaml.
```
landroid_mail: YOUR_EMAIL_IN_MY_LANDROID
landroid_pass: YOUR_PASSWORD_IN_MY_LANDROID
landroid_id: LANDROID_ID_FROM_SENSOR_sensor.landroid_m500_status
landroid_ip: LANDROID_IP_ADDRESS
landroid_sn: LANDROID_SERIAL_NUMBER
landroid_mac: LANDROID_MAC_ADDRESS
```
If you do not need this data, you can ignore it, but do not forget then delete it from Lovelace too.
If you are not using secrets.yaml, you can set them directly in landroid.yaml
